# Site settings
title: Umut TOKER's Github Blog
email: umt.toker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about some python, flask, android and OrientDB. You can
  find some useful things to develop yourself with these technologies.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://umuttoker.com" # the base hostname & protocol for your site
twitter_username: umuttoker
github_username:  umuttoker

# Build settings
markdown: kramdown
